version: '3.8'

networks:
  monitoring_network:  # Définition du réseau partagé
    driver: bridge     # Utilisation du mode bridge

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_abdel
      WORDPRESS_DB_PASSWORD: abdel123
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - monitoring_network  # Ajout du service au réseau partagé

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_abdel
      MYSQL_PASSWORD: abdel123
      MYSQL_ROOT_PASSWORD: abdel123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - monitoring_network  # Ajout du service au réseau partagé

  mysqld-exporter:
    image: prom/mysqld-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "wp_abdel:abdel123@tcp(db:3306)/wordpress_db"
    volumes:
      - ./my.cnf:/root/.my.cnf  
    depends_on:
      - db
    ports:
      - "9104:9104"
    networks:
      - monitoring_network  # Ajout du service au réseau partagé

  node-exporter:
    image: prom/node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - monitoring_network  # Ajout du service au réseau partagé

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'  # Correction du chemin
    networks:
      - monitoring_network  # Ajout du service au réseau partagé

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring_network  # Ajout du service au réseau partagé

volumes:
  wordpress_data:
  db_data:
  prometheus_data:
  grafana_data: